import { useMemo, useState } from 'react'
import { Gauge } from 'lucide-react'
import { LabPanel } from '@/components/LabPanel.tsx'
import { MetricStat } from '@/components/MetricStat.tsx'
import { SliderControl } from '@/components/SliderControl.tsx'
import { normalSamples } from '@/domain/math/random.ts'
import {
  normalMeanMap,
  sampleMean,
  weightedGaussianMean,
} from '@/domain/math/estimation.ts'
import { formatFixed } from '@/lib/format.ts'
import { scaleLinear } from '@/components/interactive/plot-utils.ts'

type EstimatorMachineProps = {
  readonly moduleId: string
}

function EstimatorMachine({ moduleId }: EstimatorMachineProps) {
  const [truth, setTruth] = useState(62)
  const [noise, setNoise] = useState(9)
  const [sampleCount, setSampleCount] = useState(12)
  const [priorStrength, setPriorStrength] = useState(3)
  const priorMean = 50
  const priorVariance = 100 / priorStrength
  const samples = useMemo(
    () =>
      normalSamples(7341 + sampleCount, sampleCount).values.map(
        (sample) => truth + sample * noise,
      ),
    [noise, sampleCount, truth],
  )
  const displaySamples = samples.slice(0, 18)
  const ml = sampleMean(samples)
  const variances = displaySamples.map((_sample, index) => 4 + index * 1.8)
  const weighted = weightedGaussianMean(displaySamples, variances)
  const map = normalMeanMap({
    sampleMeanValue: ml,
    sampleCount,
    noiseVariance: noise * noise,
    priorMean,
    priorVariance,
  })

  const cloud = useMemo(
    () =>
      normalSamples(3389, 28).values.map((sample, index) => ({
        x: truth + (sample * noise) / Math.sqrt(sampleCount),
        y: index,
      })),
    [noise, sampleCount, truth],
  )

  const title =
    moduleId === 'E2' ? 'Sensor votes and weighted means' : 'Estimator machine'

  return (
    <LabPanel
      eyebrow={moduleId}
      title={title}
      icon={<Gauge className="h-5 w-5" />}
      controls={
        <>
          <SliderControl
            label="Hidden parameter"
            variable="theta"
            value={truth}
            min={35}
            max={78}
            step={1}
            meaning="The learner sees samples generated by this hidden value, not the value itself."
            onValueChange={setTruth}
            format={(value) => value.toFixed(0)}
          />
          <SliderControl
            label="Noise"
            variable="sigma"
            value={noise}
            min={3}
            max={18}
            step={1}
            meaning="More noise spreads the sample cloud and the estimates."
            onValueChange={setNoise}
            format={(value) => value.toFixed(0)}
          />
          <SliderControl
            label="Samples"
            variable="N"
            value={sampleCount}
            min={3}
            max={50}
            step={1}
            meaning="More samples tighten the repeated-estimate cloud."
            onValueChange={setSampleCount}
            format={(value) => value.toFixed(0)}
          />
          <SliderControl
            label="Prior strength"
            variable="1/sigma_A^2"
            value={priorStrength}
            min={1}
            max={12}
            step={1}
            meaning="A stronger prior pulls MAP toward the prior mean."
            onValueChange={setPriorStrength}
            format={(value) => value.toFixed(0)}
          />
        </>
      }
    >
      <svg
        viewBox="0 0 100 64"
        className="h-56 w-full"
        role="img"
        aria-label={`Estimator machine with truth ${truth}, ML estimate ${formatFixed(ml, 1)}, MAP estimate ${formatFixed(map, 1)}.`}
      >
        <line x1="8" y1="50" x2="92" y2="50" className="stroke-border" />
        {displaySamples.map((sample, index) => (
          <circle
            key={`${sample}-${index}`}
            cx={scaleLinear({
              value: sample,
              domainMin: 25,
              domainMax: 90,
              rangeMin: 8,
              rangeMax: 92,
            })}
            cy={15 + (index % 5) * 5}
            r="1.8"
            className="fill-muted-foreground"
            opacity="0.55"
          />
        ))}
        <rect
          x="36"
          y="24"
          width="28"
          height="18"
          rx="3"
          className="fill-card stroke-border"
        />
        <text
          x="50"
          y="35"
          textAnchor="middle"
          className="fill-foreground text-[5px]"
        >
          estimator
        </text>
        <line
          x1={scaleLinear({
            value: truth,
            domainMin: 25,
            domainMax: 90,
            rangeMin: 8,
            rangeMax: 92,
          })}
          y1="6"
          x2={scaleLinear({
            value: truth,
            domainMin: 25,
            domainMax: 90,
            rangeMin: 8,
            rangeMax: 92,
          })}
          y2="50"
          className="stroke-truth"
          strokeWidth="1.2"
        />
        <circle
          cx={scaleLinear({
            value: ml,
            domainMin: 25,
            domainMax: 90,
            rangeMin: 8,
            rangeMax: 92,
          })}
          cy="50"
          r="3"
          className="fill-estimate"
        />
        <path
          d={`M ${scaleLinear({
            value: map,
            domainMin: 25,
            domainMax: 90,
            rangeMin: 8,
            rangeMax: 92,
          }).toFixed(2)} 45 l 3 6 h -6 Z`}
          className="fill-prior"
        />
        {cloud.map((point, index) => (
          <circle
            key={`${point.x}-${point.y}`}
            cx={scaleLinear({
              value: point.x,
              domainMin: 25,
              domainMax: 90,
              rangeMin: 8,
              rangeMax: 92,
            })}
            cy={56 + (index % 3) * 2}
            r="0.8"
            className="fill-estimate"
            opacity="0.35"
          />
        ))}
      </svg>
      <div className="grid gap-3 sm:grid-cols-3">
        <MetricStat
          label="Sample mean"
          value={formatFixed(ml, 1)}
          sublabel="ML for equal noise"
          tone="h0"
        />
        <MetricStat
          label="Weighted"
          value={formatFixed(weighted, 1)}
          sublabel="precision votes"
          tone="detection"
        />
        <MetricStat
          label="MAP"
          value={formatFixed(map, 1)}
          sublabel="data plus prior"
          tone="h1"
        />
      </div>
    </LabPanel>
  )
}

export { EstimatorMachine }
